(ns flutter-cljd.inherited-keys)

(def enabled {:key :enabled :default-value true})
(def button-context {:key :button-context :default-value {}})
(def enable-feedback {:key :enable-feedback :default-value false})
(def exclude-from-semantics {:key :exclude-from-semantics :default-value false})
(def can-request-focus {:key :can-request-focus :default-value true})
(def autofocus {:key :autofocus :default-value false})
